import type { User, Post, Notification } from './types';

export const currentUser: User = {
  id: 'user-1',
  name: 'Alex Johnson',
  avatar: '#4f46e5',
  bio: 'Software developer & photography enthusiast 📷',
};

export const initialPosts: Post[] = [
  {
    id: 'post-1',
    userId: 'user-2',
    userName: 'Sarah Williams',
    userAvatar: '#e11d48',
    content: 'Just finished a 10km run this morning! Feeling amazing 🏃‍♀️ The weather was perfect and I beat my personal record. Who else loves morning workouts?',
    likes: 42,
    likedByMe: false,
    time: '2 hours ago',
    comments: [
      {
        id: 'comment-1',
        userId: 'user-3',
        userName: 'Mike Chen',
        userAvatar: '#0891b2',
        text: 'That\'s incredible! What\'s your pace?',
        time: '1 hour ago',
      },
      {
        id: 'comment-2',
        userId: 'user-1',
        userName: 'Alex Johnson',
        userAvatar: '#4f46e5',
        text: 'Congrats! Keep it up! 💪',
        time: '45 minutes ago',
      },
    ],
  },
  {
    id: 'post-2',
    userId: 'user-1',
    userName: 'Alex Johnson',
    userAvatar: '#4f46e5',
    content: 'Working on a new Next.js project today. The app router is really growing on me! Anyone else making the switch from pages router? 🚀',
    likes: 28,
    likedByMe: false,
    time: '4 hours ago',
    comments: [
      {
        id: 'comment-3',
        userId: 'user-4',
        userName: 'Emma Davis',
        userAvatar: '#16a34a',
        text: 'App router is the future! Love the server components.',
        time: '3 hours ago',
      },
    ],
  },
  {
    id: 'post-3',
    userId: 'user-3',
    userName: 'Mike Chen',
    userAvatar: '#0891b2',
    content: 'Just tried the new coffee shop downtown ☕ Their oat milk latte is absolutely divine. Perfect place to work remotely. 10/10 would recommend!',
    likes: 67,
    likedByMe: true,
    time: '6 hours ago',
    comments: [],
  },
  {
    id: 'post-4',
    userId: 'user-4',
    userName: 'Emma Davis',
    userAvatar: '#16a34a',
    content: 'Excited to share that I just got promoted to Senior Engineer! 🎉 It\'s been a long journey but totally worth it. Thank you to everyone who supported me along the way!',
    likes: 156,
    likedByMe: false,
    time: '1 day ago',
    comments: [
      {
        id: 'comment-4',
        userId: 'user-2',
        userName: 'Sarah Williams',
        userAvatar: '#e11d48',
        text: 'Congratulations! You deserve it! 🎊',
        time: '23 hours ago',
      },
      {
        id: 'comment-5',
        userId: 'user-1',
        userName: 'Alex Johnson',
        userAvatar: '#4f46e5',
        text: 'Amazing news! Well deserved Emma!',
        time: '22 hours ago',
      },
      {
        id: 'comment-6',
        userId: 'user-3',
        userName: 'Mike Chen',
        userAvatar: '#0891b2',
        text: 'So proud of you! 🙌',
        time: '20 hours ago',
      },
    ],
  },
  {
    id: 'post-5',
    userId: 'user-5',
    userName: 'Jordan Lee',
    userAvatar: '#d97706',
    content: 'Beautiful sunset from my balcony tonight 🌅 Sometimes you just need to stop and appreciate the little things in life. Nature never disappoints.',
    likes: 89,
    likedByMe: false,
    time: '2 days ago',
    comments: [
      {
        id: 'comment-7',
        userId: 'user-2',
        userName: 'Sarah Williams',
        userAvatar: '#e11d48',
        text: 'Stunning! Where do you live?',
        time: '2 days ago',
      },
    ],
  },
];

export const initialNotifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'like',
    fromUser: 'Sarah Williams',
    message: 'liked your post about Next.js',
    time: '5 minutes ago',
    read: false,
  },
  {
    id: 'notif-2',
    type: 'comment',
    fromUser: 'Mike Chen',
    message: 'commented on your post: "App router is amazing!"',
    time: '20 minutes ago',
    read: false,
  },
  {
    id: 'notif-3',
    type: 'follow',
    fromUser: 'Emma Davis',
    message: 'started following you',
    time: '1 hour ago',
    read: false,
  },
  {
    id: 'notif-4',
    type: 'like',
    fromUser: 'Jordan Lee',
    message: 'liked your comment on Emma\'s post',
    time: '3 hours ago',
    read: true,
  },
  {
    id: 'notif-5',
    type: 'comment',
    fromUser: 'Sarah Williams',
    message: 'replied to your comment: "Great point!"',
    time: '5 hours ago',
    read: true,
  },
  {
    id: 'notif-6',
    type: 'follow',
    fromUser: 'Chris Park',
    message: 'started following you',
    time: '1 day ago',
    read: true,
  },
];
